version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: projetouser
      WORDPRESS_DB_PASSWORD: projetopass
      WORDPRESS_DB_NAME: projetodb

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: projetodb
      MYSQL_USER: projetouser
      MYSQL_PASSWORD: projetopass
      MYSQL_ROOT_PASSWORD: GAud4mZby8F3SD6P
